[tool.ruff]

select = ["E", "F", "W", "C", "S", "I", "TCH"]

# E501 rule checks for maximum line length
ignore = ["E501"]

target-version = "py311"
line-length = 100

[tool.coverage.report]
# unit tests fails if the total coverage measurement is under this threshold value
fail_under = 40
